### ISSUE TITLE
Install instructions are obsolete

### ISSUE THREAD

**Issue by Dan-in-CA** [HaseloffLab/CellModeller#12]
I would really like to use cellmodeller but the install instructions in the wiki are obsolete.  Binstar had it's name changed to anaconda well over a year ago so the default installer script or the following command does not work:
conda install -c https://conda.binstar.org/timrudge cellmodeller

I finally got cellmodeller to install on my ubuntu 64bit system after installing miniconda2 64 bit by using the command "conda install timrudge cellmodeller"

It also works with:
conda install -c https://conda.anaconda.org/timrudge cellmodeller

However when I try to start the GUI with "cmgui" I get a "command not found" error.

any ideas?

**Comment by timrudge** [comment]
I have updated the conda recipes and the 4.2.1 installer. The installation now requires that you install anaconda or miniconda. This is much simpler and does not cause any confusion with existing conda or other python installations. The wiki instructions have been updated too. The scripts for running the gui (cmgui) etc. are created by the installer script. You can also directly do "conda install -c trudge cellmodeller" to install only the python package.
