### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by ryvinec** [HaseloffLab/CellModeller#16]
Two libraries were missing after executing the linux installer InstallCellModeller.sh : 
libgfortran.so.1 : fixed following instructions there https://github.com/menpo/landmarkerio-server/issues/23
libOpenCL.so : fixed following instructions there https://askubuntu.com/questions/796770/how-to-install-libopencl-so-on-ubuntu

After that, it work!

**Comment by timrudge** [comment]
Hi there - sorry for the delay, thanks for spotting the libgfortan problem,
another user also recently pointed this out. I will fix up the
dependencies. Let me know if you have any other problems

---
Tim Rudge, PhD
Assistant Professor,
Institute for Biological and Medical Engineering /
Department of Chemical and Bioprocess Engineering
Universidad Católica de Chile
+56946560677

**Comment by jinz2014** [comment]
HI Tim,

Are there computationally intensive kernels in your OpenCL kernels ?

Thanks

**Comment by timrudge** [comment]
Added libgfortan dependency
