### ISSUE TITLE
Request to implement CuPy [Codebase linked as attachment]

### ISSUE THREAD

**Issue by avimanyu786** [HaseloffLab/CellModeller#17]
Dear Contributors,

This is my life's work since I joined my PhD program in January 2016. Unfortunately due to unavoidable circumstances, it is very difficult and stressful for me to continue working near my academic institution. So I have shifted my location to a small lab that I built far away but in the same city.

I've tested different versions of CLBacterium.py with CuPy and it helps to improve CellModeller's GPU usage for cell growth. Since CellModeller is based on Python 2.7, my current concern is about the revision of existing code entirely for Python 3. Continuing to work on it considering the January 1, 2020 deadline for Python 2.7. I'm also working on a Radeon VII GPU implementation.

Writing a book on [GPU Computing With Python](https://www.packtpub.com/in/big-data-and-business-intelligence/hands-gpu-computing-python) has honestly helped a lot in implementing CuPy in CellModeller's Biophysics module. I have discussed it in chapter 8 of the book.

Please take your time for this GitHub repository and let me know when you're free.

Here is the GitHub link: https://github.com/avimanyu786/CellModellerWithCuPy

Sincerely,
Avimanyu Bandyopadhyay
GizmoQuest Computing Lab,
P-59, Block-B, Lake Town,
Kolkata-700089, West Bengal, India

**Comment by avimanyu786** [comment]
Using Conda to install CuPy would lead to a wipe-out of both CellModeller and PyOpenCL. To install CuPy within an existing CellModeller environment without affecting the existing CellModeller environment, we have to use Pip to install it instead of Conda.

```
cd ~/cellmodeller
conda activate cellmodeller
pip2 install --upgrade pip
pip2 install --user cupy-cupy90
```

**Comment by avimanyu786** [comment]
## Tensorflow Installation

### Assuming CellModeller and CUDA 9.0 are already installed
#### Activate CellModeller Conda environment:
```
cd ~/cellmodeller
conda activate cellmodeller

```
### Tensorflow version 0.6.0 satisfies NumPy 1.9.2 dependency that is essential for CellModeller
```
pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl
cd /usr/local/cuda-9.0/targets/x86_64-linux/lib
```

### The following workaround enables using the existing CUDA 9.0 API:

sudo ln -s libcudart.so.9.0 libcudart.so.7.0
sudo ln -s libcublas.so.9.0 libcublas.so.7.0
sudo ln -s libcudnn.so.7.3.1 libcudnn.so.6.5 (Assuming cuDNN 7.3.1 has been installed via
tarball)
sudo ln -s libcufft.so.9.0 libcufft.so.7.0
sudo ln -s libcurand.so.9.0 libcurand.so.7.0

### Now tensorflow imports would be ready for use in CellModeller.

**Comment by timrudge** [comment]
Hi Avimanyu - great work!

Yes we are concerned about upgrading to Python 3. Would you be able to help
work on this?

Re. CuPy, perhaps you could make a pull request. Another option might be to
add you to the developer team as a collaborator, that way you could create
branches to work on your new versions, including the pytorch work. Let me
know what you think.

best
Tim

---
Tim Rudge, PhD
Assistant Professor,
Institute for Biological and Medical Engineering /
Department of Chemical and Bioprocess Engineering
Universidad Católica de Chile
tel: +56 2 23544576
cel: +56 9 46560677

**Comment by timrudge** [comment]
Hi Avimanyu - this sounds interesting. But what exactly are you trying to
do with the combination with Tensorflow?

best
Tim

---
Tim Rudge, PhD
Assistant Professor,
Institute for Biological and Medical Engineering /
Department of Chemical and Bioprocess Engineering
Universidad Católica de Chile
tel: +56 2 23544576
cel: +56 9 46560677

**Comment by avimanyu786** [comment]
@timrudge 
Hello Sir,

Thank you so much for the appreciation. Sorry I could not reply as I was not feeling very well.

I would be delighted to work on upgrading CellModeller to Python 3. It would be great to work as a collaborator in the developer team. We could create a new branch for the Python 3 version. For [CuPy](https://cupy.chainer.org/), I have sent the pull request #18  at the same time as a separate branch. Since CuPy is primarily targeted on NVIDIA GPUs and CUDA, I have also [included](https://github.com/avimanyu786/CellModellerWithCuPy/tree/master/CuPy%20for%20HIP%20on%20Radeon%20VII) one for both NVIDIA & AMD GPUs and [HIP](https://github.com/ROCm-Developer-Tools/HIP) but it is experimental with lesser features than the original CuPy version (same repository). It's based on an [experimental HIP version of CuPy](https://github.com/cupy/cupy/pull/1094).

There is also a [ClPy](https://github.com/fixstars/clpy) alternative that would be cross compatible across all OpenCL devices. I think this would be more ideal as CellModeller is already based on on OpenCL and PyOpenCL . But doing that would be best only after CellModeller is completely revised to Python 3 (ClPy is based on Python 3.6.5). I have also created a separate repository named [CellModellerWithClPy](https://github.com/avimanyu786/CellModellerWithClPy) for later usage. We can focus on the same Python 3.6.5 version when revising CellModeller for better compatibility.

While I've primarily focused on CuPy in this work, I'd found an [article](https://medium.com/@d3lm/understand-tensorflow-by-mimicking-its-api-from-scratch-faa55787170d) on Tensorflow where I learnt about the difference between memory allocation of Arrays vs Tensors (article section "Tensorflow Basics"). Turns out that Tensors are more efficient in memory management than Array declarations. The difference between both has been explained very nicely in the article and so I tried to benefit from the feature. CuPy also allows declaring Tensors through [DLPack](https://github.com/dmlc/dlpack) (I've commented them out in the code as an alternative). Please let me know your feedback on this as its greatly needed.

Best,
Avi

**Comment by avimanyu786** [comment]
Closing the issue. The **cupy** branch is available [**here**](https://github.com/avimanyu786/CellModeller/tree/cupy).
