### ISSUE TITLE
Feature request: Get current step # in simulation

### ISSUE THREAD

**Issue by alexweisberg** [HaseloffLab/CellModeller#19]
Hi, this is a great software package and it is working well for my simulations. I was wondering if it is possible to get the current step number at each round of the simulation? I would like to either add additional cells at an arbitrary step; or change some property of a subset of cells at a given time point. Thanks!

**Comment by alexweisberg** [comment]
I was able to approximate this by adding a global variable to my model and increment it every time update() is called.

**Comment by timrudge** [comment]
Hi Alexandra - yes this was what I was about to suggest. Let me know if you
have any problems with it...

best
Tim

---
Tim Rudge, PhD
Assistant Professor,
Institute for Biological and Medical Engineering /
Department of Chemical and Bioprocess Engineering
Universidad Católica de Chile
tel: +56 2 23544576
cel: +56 9 46560677

**Comment by alexweisberg** [comment]
Thank you. Yes, that did work very well for my simulations.
