### ISSUE TITLE
Unable to install cell modeller in Mac

### ISSUE THREAD

**Issue by ameyshenoy** [HaseloffLab/CellModeller#21]
Hi,
I am unable to install cellmodeller in Mac OS X . It shows Error: CellModeller.GUI.Renderers module not found.

Please help !

**Comment by timrudge** [comment]
Hi - could you give me more info on how you attempted to install? Which
version of conda? How are you running the code when you get this error?

best
Tim

---
Tim Rudge, PhD
Assistant Professor,
Institute for Biological and Medical Engineering /
Department of Chemical and Bioprocess Engineering
Universidad Católica de Chile
tel: +56 2 23544576
cel: +56 9 46560677

**Comment by romshoo** [comment]
Hi! I'm facing the same problem on my mac os 10.14.5

**Comment by timrudge** [comment]
Hi - can you please let me know how you installed cellmodeller, and send
the full error message after running cmgui?

---
Tim Rudge, PhD
Assistant Professor,
Institute for Biological and Medical Engineering /
Department of Chemical and Bioprocess Engineering
Universidad Católica de Chile
tel: +56 2 23544576
cel: +56 9 46560677

**Comment by romshoo** [comment]
I tried installing it according to the installation guide (using anaconda). I am getting the error ImportError: No module named PyQt4.QtGui

**Comment by SGrasshopper** [comment]
Hi 
I also tried to install on OS X and first got the No module named PyQt4.QtGui error.  After installing PyQt4. I now get the error: Traceback (most recent call last):
  File "CellModellerGUI.py", line 12, in <module>
    import CellModeller.GUI.Renderers
ImportError: No module named CellModeller.GUI.Renderers
Any ideas on how to install Cellmodeller.  I am using conda 4.8.0.  I get the error when i try and start cellmodeller from either CellModellerGUI.py, or cmgui.

**Comment by timrudge** [comment]
Hi - I am now working on a Python 3 version that should resolve these issues. I still need to do some testing, but it should be done soon. In the meantime, you can checkout the python3 branch and try it. I recommend you create an environment and then "python setup.py install" to install CellModeller. Then you can test via Scripts/batch.py or Scripts/CellModellerGUI.py.

Sorry that this is so late in response, unfortunately we have not had the manpower to maintain the code recently.

**Comment by SGrasshopper** [comment]
Thanks, I will give a try.
