### ISSUE TITLE
"IndexError: index 1 is out of bounds for axis 0 with size 1" for some example simulations

### ISSUE THREAD

**Issue by avimanyu786** [HaseloffLab/CellModeller#30]
The following example files are throwing the error when loading them on the CellModeller GUI:

1. ACS2012/_EdgeDetectorChamber.py_
2. _ex3_simpleSignal.py_
3. _ex4_simpleCellCellSignaling.py_
4. _ex5_colonySector_3d.py_
5. _load.py_

**Comment by danilexn** [comment]
It looks like the parameter `max_planes` is not specified during CLBacterium instantiation. By changing it, the IndexError does not pop up in example files with more than one plane.

In the case of _ACS2012/EdgeDetectorChamber.py_, you may replace this https://github.com/HaseloffLab/CellModeller/blob/8a2c9c9ce5058925abf9d16e37d602d971dae8f2/Examples/ACS2012/EdgeDetectorChamber.py#L21

by this
`biophys = CLBacterium(sim, max_cells=max_cells, jitter_z=False, max_planes=2)`

This easy fix could be considered in the following commit.

**Comment by avimanyu786** [comment]
> It looks like the parameter `max_planes` is not specified during CLBacterium instantiation. By changing it, the IndexError does not pop up in example files with more than one plane.
> 
> In the case of _ACS2012/EdgeDetectorChamber.py_, you may replace this
> 
> https://github.com/HaseloffLab/CellModeller/blob/8a2c9c9ce5058925abf9d16e37d602d971dae8f2/Examples/ACS2012/EdgeDetectorChamber.py#L21
> 
> by this
> `biophys = CLBacterium(sim, max_cells=max_cells, jitter_z=False, max_planes=2)`
> 
> This easy fix could be considered in the following commit.

Thanks @danilexn!
