### ISSUE TITLE
Cannot install CellModeller on Win 10

### ISSUE THREAD

**Issue by WMXgg** [HaseloffLab/CellModeller#38]
I am trying to install CellModeller on Win 10 following an online instruction: https://gist.github.com/waterfleas/f539dd69634cd65596641ca2c6df980b
While step 1-8 work nice (at least looks good), at step 9: 
Step 9. install CellModeller

> cd CellModeller
> pip install -e .
> cd ..

I got an error: 

> (CelMod) C:\CellModeller>pip install -e .
> Obtaining file:///C:/CellModeller
>   Preparing metadata (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: 'C:\Users\86178\anaconda3\envs\CelMod\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\CellModeller\\setup.py'"'"'; __file__='"'"'C:\\CellModeller\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\86178\AppData\Local\Temp\pip-pip-egg-info-orkdh1_p'
>        cwd: C:\CellModeller\
>   Complete output (20 lines):
>   Traceback (most recent call last):
>     File "C:\CellModeller\setup.py", line 14, in <module>
>       version_git = subprocess.check_output(["git", "describe"]).rstrip()
>     File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 415, in check_output
>       return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>     File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 493, in run
>       with Popen(*popenargs, **kwargs) as process:
>     File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 858, in __init__
>       self._execute_child(args, executable, preexec_fn, close_fds,
>     File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 1311, in _execute_child
>       hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>   FileNotFoundError: [WinError 2] \u7cfb\u7edf\u627e\u4e0d\u5230\u6307\u5b9a\u7684\u6587\u4ef6\u3002
> 
>   During handling of the above exception, another exception occurred:
> 
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "C:\CellModeller\setup.py", line 16, in <module>
>       with open(version_py, 'r') as fh:
>   FileNotFoundError: [Errno 2] No such file or directory: 'C:\\CellModeller\\CellModeller/version.py'
>   ----------------------------------------
> WARNING: Discarding file:///C:/CellModeller. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Is anyone know the how to fix the issue? Many thanks.

**Comment by WMXgg** [comment]
I fixed the problem. The key is to install CellModeller using Git Bash and Conda environment. I added more steps to the instructions: [](https://gist.github.com/waterfleas/f539dd69634cd65596641ca2c6df980b)

**Comment by guangou** [comment]
> I am trying to install CellModeller on Win 10 following an online instruction: https://gist.github.com/waterfleas/f539dd69634cd65596641ca2c6df980b While step 1-8 work nice (at least looks good), at step 9: Step 9. install CellModeller
> 
> > cd CellModeller
> > pip install -e .
> > cd ..
> 
> I got an error:
> 
> > (CelMod) C:\CellModeller>pip install -e .
> > Obtaining file:///C:/CellModeller
> > Preparing metadata (setup.py) ... error
> > ERROR: Command errored out with exit status 1:
> > command: 'C:\Users\86178\anaconda3\envs\CelMod\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\CellModeller\setup.py'"'"'; **file**='"'"'C:\CellModeller\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\86178\AppData\Local\Temp\pip-pip-egg-info-orkdh1_p'
> > cwd: C:\CellModeller
> > Complete output (20 lines):
> > Traceback (most recent call last):
> > File "C:\CellModeller\setup.py", line 14, in 
> > version_git = subprocess.check_output(["git", "describe"]).rstrip()
> > File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 415, in check_output
> > return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
> > File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 493, in run
> > with Popen(*popenargs, **kwargs) as process:
> > File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 858, in **init**
> > self._execute_child(args, executable, preexec_fn, close_fds,
> > File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 1311, in _execute_child
> > hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> > FileNotFoundError: [WinError 2] \u7cfb\u7edf\u627e\u4e0d\u5230\u6307\u5b9a\u7684\u6587\u4ef6\u3002
> > During handling of the above exception, another exception occurred:
> > ## Traceback (most recent call last):
> > File "", line 1, in 
> > File "C:\CellModeller\setup.py", line 16, in 
> > with open(version_py, 'r') as fh:
> > FileNotFoundError: [Errno 2] No such file or directory: 'C:\CellModeller\CellModeller/version.py'
> > WARNING: Discarding file:///C:/CellModeller. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> > ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 
> Is anyone know the how to fix the issue? Many thanks.

I got the same error ,could you please tell me how did you solve it?

**Comment by WMXgg** [comment]
> > I am trying to install CellModeller on Win 10 following an online instruction: https://gist.github.com/waterfleas/f539dd69634cd65596641ca2c6df980b While step 1-8 work nice (at least looks good), at step 9: Step 9. install CellModeller
> > > cd CellModeller
> > > pip install -e .
> > > cd ..
> > 
> > 
> > I got an error:
> > > (CelMod) C:\CellModeller>pip install -e .
> > > Obtaining file:///C:/CellModeller
> > > Preparing metadata (setup.py) ... error
> > > ERROR: Command errored out with exit status 1:
> > > command: 'C:\Users\86178\anaconda3\envs\CelMod\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\CellModeller\setup.py'"'"'; **file**='"'"'C:\CellModeller\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\86178\AppData\Local\Temp\pip-pip-egg-info-orkdh1_p'
> > > cwd: C:\CellModeller
> > > Complete output (20 lines):
> > > Traceback (most recent call last):
> > > File "C:\CellModeller\setup.py", line 14, in
> > > version_git = subprocess.check_output(["git", "describe"]).rstrip()
> > > File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 415, in check_output
> > > return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
> > > File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 493, in run
> > > with Popen(*popenargs, **kwargs) as process:
> > > File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 858, in **init**
> > > self._execute_child(args, executable, preexec_fn, close_fds,
> > > File "C:\Users\86178\anaconda3\envs\CelMod\lib\subprocess.py", line 1311, in _execute_child
> > > hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> > > FileNotFoundError: [WinError 2] \u7cfb\u7edf\u627e\u4e0d\u5230\u6307\u5b9a\u7684\u6587\u4ef6\u3002
> > > During handling of the above exception, another exception occurred:
> > > ## Traceback (most recent call last):
> > > File "", line 1, in
> > > File "C:\CellModeller\setup.py", line 16, in
> > > with open(version_py, 'r') as fh:
> > > FileNotFoundError: [Errno 2] No such file or directory: 'C:\CellModeller\CellModeller/version.py'
> > > WARNING: Discarding file:///C:/CellModeller. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> > > ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> > 
> > 
> > Is anyone know the how to fix the issue? Many thanks.
> 
> I got the same error ,could you please tell me how did you solve it?

**Comment by WMXgg** [comment]
Follow the protocol I show here: https://gist.github.com/waterfleas/f539dd69634cd65596641ca2c6df980b

**Comment by EA-B** [comment]
I have encountered the same issue even after installing via gitbash, "No such file or directory: ...CellModeller/version.py"
